#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

if [ $# -le 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	filePath=$1
	ip=$2
	user=$3
	keyPath=$4
	scp -i "$keyPath" "$filePath" "$user"@"$ip":~/ -o StrictHostKey=no
fi
