#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect requirements

apt-get update -y
apt-get install -y nginx

ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.html
service nginx restart
