#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect requirements

apt update
apt install -y nginx

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
	return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

kill -s HUP "$(cat /var/run/nginx.pid)"
