#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

apt-get update -y
apt install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
echo "location = /redirect_me {
		return 301 https://www.google.com;
     }" >> /etc/nginx/sites-available/default

service nginx restart
