#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

sudo apt update

sudo apt install -y nginx

echo "Hello  World!" | sudo tee /var/www/html/index.html

sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 http://google.com;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF'

sudo service nginx restart
