#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that
#+ contains the string Ceci n'est pas une page.

apt-get update -y
apt install -y nginx
ufw allow 'Nginx HTTP'

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
touch /etc/nginx/html/404code.html

echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404code.html

echo "server {
	listen 80;
	listen [::]:80 default_server;
	root   /etc/nginx/html;
	index  index.html index.htm;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	error_page 404 /404code.html;
	location /404 {
		root /etc/rginx/html;
		internal;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
