#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that
#+ contains the string Ceci n'est pas une page.

apt-get update -y
apt install -y nginx
ufw allow 'Nginx HTTP'

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
touch /etc/mginx/html/404.h

echo "Hello World!" > /etc/nginx/html/index.html

echo "server {
	listen 80;
	listen [::]:80 default_server;
	
	root  /etc/nginx/html;
	index index.html index.htm;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
