#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements asked in this task

sudo apt update

sudo apt install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    add_header X-Served-By \"\$hostname\";

    error_page 404 /404.html;

    location = /404.html {
        root /var/www/html;
        internal;
    }

    location /redirect_me {
        return 301 http://google.com;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF'

sudo service nginx restart
