#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements asked in this task

apt-get update -y
apt-get install -y nginx

mkdir /var/www/html
touch /var/www/html/index.html
touch /var/www/html/404code.html

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root   /var/www/html;
	index  index.html index.htm;

	add_header X-Served-By $hostname;

	location /redirect_me {
           return 301 https://www.youtube.com;
	}

	error_page 404 /404.html;
	location /404 {
            root /var/www/html;
            internal;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
