#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt-get update
sudo apt-get install -y haproxy

sudo bash -c "cat > /etc/haproxy/haproxy.cfg <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    mode http
    timeout client 10s
    timeout connect 5s
    timeout server 10s
    timeout http-request 10s

frontend web
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server 290943-web-01:80 35.174.185.16 check
    server 290943-web-02:80 34.229.72.168 check
EOF"

sudo systemctl restart haproxy
