#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it

Date=$(date +%d-%m-%Y)

dumpFile=backup.sql

archiveName="$Date".tar.gz

mysqldump --all-databases --user=root --password="$1" > "$dumpFile"

tar -czvf "$archiveName" "$dumpFile"

rm "$dumpFile"
