#!/usr/bin/env bash
# Fix port configration of Ubuntu container's Nginx installation

nginx_conf="/etc/nginx/sites-available/default"
sed -i 's/listen [0-9]\+/listen 80/' "$nginx_conf"
service nginx restart
