#!/usr/bin/env bash
# Fix port configration of Ubuntu container's Nginx installation

rm /etc/nginx/sites_enabled/default
ln -s /etc/sites_available/default /etc/nginx/sites_enabled/default
service nginx restart
