#!/usr/bin/env bash
#  Bash (init) script 101-manage_my_process that manages manage_my_process

arg=$1
if [ "$arg" == "start" ]
then
	bash ./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"

elif [ "$arg" == "stop" ]
then
	pkill -f "./manage_my_process"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"

elif [ "$arg" == "restart" ]
then
	pkill -f "./manage_my_process"
	rm /var/run/my_process.pid
	bash ./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"

else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
