#!/usr/bin/env bash
# Bash script that displays the PID, along with the process name, of processes whose name contain the word bash

bash_pids=$(pgrep bash)
for pid in $bash_pids;
do
	echo "$pid bash"
done 
