#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd, using the while loop + IFS

while IFS=: read -r user pass uid gid uidinfo dir cmd
do
	echo "The user $user is part of the $gid gang, lives in $dir and rides $cmd. $uid's place is protected by the passcode $pass, more info about the user here: $uidinfo"
done < /etc/passwd
