#!/usr/bin/env bash
# Configure machine to our needs so that you can connect to a server
#+ without typing a password

echo "Host *
	  IdentityFile ~/.ssh/school
	  PasswordAuthentication no
" > ~/.ssh/config
